language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t tag/docker-react -f Dockerfile.dev . 
script:
    - docker run -e CI=true tag/docker-react npm run test
